function [H, p] = fc_nsp_Hidx(fc_rearranged, cluster_size, cluster_number)
%FC_NSP_HIDX This function calculates integration, segregation indices from
%the rearranged FC matrix generated by nested spectral partitioning (NSP).
%This function is adapted from the scripts in Wang et al. (2021).
%
% Key reference(s):
% Wang, R., Liu, M., Cheng, X., Wu, Y., Hildebrandt, A., & Zhou, C. (2021).
% Segregation, integration, and balance of large-scale resting brain
% networks configure different cognitive abilities. Proceedings of the
% National Academy of Sciences, 118(23), e2022288118.
%
%   [H, p] = fc_nsp_Hidx(fc_rearranged, cluster_size, cluster_number)
%
% Input:
%  Inputs are exactly the outputs of fc_nested_spectral_partitioning.m
%  fc_rearranged:   rearranged functional connectivity matrix
%  cluster_size:    number of regions in each cluster, for each mode
%  cluster_number:  (1 / cluster_number) is the rough number of regions in
%                   one cluster
% Output:
%  H:       hierarchical components
%  p:       correction 

% Exclude negative correlations
fc_rearranged(fc_rearranged < 0) = 0;

% Eigen-decomposition of the FC
[eigvecs, eigvals] = eig(fc_rearranged);

% use the squared Lambda
eigvals(eigvals < 0) = 0;
eigvals_sqr = eigvals.^2;

N = size(fc_rearranged,1);
p = zeros(1,N);
for i = 1:sum(cluster_number < 1)
    p(i) = sum(abs(cluster_size{i} - 1/cluster_number(i)))/N;%% modular size correction
end
H = fliplr(diag(eigvals_sqr)').*cluster_number.*(1-p);

%Hin = sum(H(1))/N;
%Hse = sum(H(2:N))/N;
%Hb = Hin - Hse;

end